---
apiVersion: apps/v1
# Тип объекта
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  # селектор
  selector:
    matchLabels:
      app: my-app
  # стратегия обновления
  strategy:
    # тип
    type: RollingUpdate
    rollingUpdate:
      # дополнительная реплика. Можно писать в процентах: 10%
      maxSurge: 1
      # максимум сколько потушить для обновления
      maxUnabailable: 1
  template:
    metadata:
      # установить label
      labels:
        app: my-app
    spec:
      containers:
        - image: nginx:1.12
        name: nginx
        ports:
          # открыть порт контейнера
          - containerPort: 80