apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
        - image: nginx:1.12
          name: nginx
          ports:
          - name: http     # имя порта
            containerPort: 80
          volumeMounts:
          - name: config1
            mountPath: /etc/nginx/conf.d/
      volumes:
      - name: config1
        configMap:
          name: cm1
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc1
spec:
  selector:
    app: web1
  ports:
  - name: http
    port: 80
    targetPort: http # подставляется номер порта из APP: WEB
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
data:
  default.conf: |   # пайп говорит о том, что у нас многострочная переменная и дальше нужно воспринимать все, как одну переменную
    server {
        listen 80 default_server;
        server_name  _;
        default_type text/plain;
        location / {
            return 200 '$hostname\n';
        }
    }